### PR TITLE
l10ns set was crashing 'ref is undefined'

### PR DESCRIPTION
**Pull request by focusaurus**
when calling `l10ns set SOME__KEY -l es-EC "Some Value"`

### CODE REVIEW

**Comment by tinganho** [comment]
@focusaurus you probably already know this. But you can use the CLI set method using a latest reference instead of the localization key.

```shell
l10ns log
@1 SOME_KEY_1 | SOME_VALUE_1
@2 SOME_KEY_2 | SOME_VALUE_2
@3 SOME_KEY3 | SOME_VALUE_3
...
```
Now, you can set a new value with @-reference.
```shell
10ns set @1 "SOME_VALUE"
```
You can also do the same with a search reference(%-reference):

```shell
l10ns log
%1 SOME_KEY_1 | SOME_VALUE_1
%2 SOME_KEY_2 | SOME_VALUE_2
%3 SOME_KEY3 | SOME_VALUE_3
...
```shell
10ns set %1 "SOME_VALUE"
```

I will release your fix in part of an another big release 1.1 very soon.

**Comment by focusaurus** [comment]
Yeah, I'd be interested to hear your thoughts and recommendations on workflow for generating a file to send to a translation company. I built a little prototype app with l10ns and then I exported all my keys to files like NAV__REGISTER.en-US.txt and NAV__REGISTER.es-EC.txt with the idea that I would put English in both of those, send them to an agency, and have a translator translate the English to Spanish in the .es-EC.txt files, then send them back to me, and I'd use a script around l10ns to get the new values back into the l10ns json files. Not sure if I just sent the l10ns .json files directly a translation agency would  A) know what to do with them or B) easily be able to find the English versions that are the source to be translated. Researching other projects it seems like the GNU gettext .po format is widely-used along with a bunch of others.

**Comment by tinganho** [comment]
@focusaurus It sounds like a good idea for A) I think they will have no problem understand what to do with them except when to translate more complex format such as plural and select format. So you might need to learn them how to use it. But let say that you support the Russian language, where they have 4 plural forms. They need to know how to map CLDR's plural form with their general sense of plural forms. So you need to send them what `one`, `few`, `many` and `other` means. I.e. just visiting the translation interface and paste the screenshot(It has some example numbers foreach plural form):

screen shot 2015-02-10 at 9 20 44 am

For B) I think they will have no problem finding the English version. At least if they are using it for the first time and you have pasted the English translation into the Spanish. For the second time, when they have override the English translation with the Spanish it might be inefficient to find the English source. In L10ns you will always have the English translation shown up in your face, for easy reference.

Technology wise, as long as you just touch the `value` property in each entry on the `.json`-storage files, L10ns will have no problem dealing with it.

I highly don't recommend using gettext. It doesn't support pluralization with 2 plural words. So localizing strings like `I like 2 cats and 1 dog` is not possible in gettext. But also it doesn't have built-in support for number formatting and different numbering system. So "I like 2,000 cats" becomes "2000 cats" in gettext. And it is not even possible to pluralize things properly in Arabic since Arabic uses Indian-Arabic numbers. Also to use context based formatting along with plural formatting is also very hard in gettext. So "He/She likes 1 cat" is not supported without ugly hacking get text.

If you really have time, you can just run `l10ns interface` on a dedicated server and just tell them to visit that website to translate things.

It would be good if you could open-source this solution. I have heard at least 2 people requesting this feature before.

**Comment by tinganho** [comment]
@focusaurus I'm just curious which company/service you use for localizing content?

**Comment by focusaurus** [comment]
Don't know yet. Still researching the landscape then will have to find a
translation agency.

**Pull request merged**
